name: publish
on: [push]
jobs:
  publish-env-crucible-docker-image:
    runs-on: crucible-one, crucible-two
    permissions:
      packages: write
      contents: read
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

    -
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          yaml:
            - '*.yml'
          docker:
            - '*Docker*'

    -
      name: Set up Docker Buildx
      if: steps.filter.outputs.yaml == 'true' || steps.filter.outputs.docker == 'true'
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to GitHub Container Registry
      if: steps.filter.outputs.yaml == 'true' || steps.filter.outputs.docker == 'true'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Build and push env-crucible container...
      if: steps.filter.outputs.yaml == 'true' || steps.filter.outputs.docker == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64, linux/amd64
        push: true
        tags: ghcr.io/rainfall/env-crucible:latest
      