name: On Schedule

on:
  schedule:
    - cron:  '0 23 * * 6'

jobs:
  
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publisher.yml
    secrets: inherit
    