name: Build and Publish
on: 
  workflow_call:

permissions:
      actions: write
      contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Base Image Checker
        id: current_image
        uses: giggio/docker-image-update-checker@v2
        with:
          base-image: mcr.microsoft.com/devcontainers/rust:dev-bullseye
          image: ghcr.io/${{ github.repository }}-checker:latest
          verbose: true
        continue-on-error: true

      - name: Cache Deletion
        if: steps.current_image.needs_updating == 'true'
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}

          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R $REPO  | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO  --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  

  main:
    runs-on: self-hosted
    needs: check
    permissions:
      packages: write

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Docker Buildx Setup
      uses: docker/setup-buildx-action@v2

    - name: Docker Cache Setup
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: GitHub Container Registry Authenticator
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Crucible Builder
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64, linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    
    - name: Checker Builder
      uses: docker/build-push-action@v4
      with:
        context: ./.tracking/
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository }}-checker:latest

    -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Cache Mover
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache  
      
