name: Check for push valid push events
on: 
  push:   
    branches: [ "main" ]
    paths:
      - '**.yml'
      - 'Dockerfile'
  pull_request:
    branches: ["main"]
    paths: 
      - '**.yml'
      - 'Dockerfile'

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish.yml
    secrets: inherit