name: Check for push valid push events
on: 
  push:   
    branches: [ "main" ]
    paths:
      - '**.yml'
      - 'Dockerfile'
  pull_request:
    branches: ["main"]
    paths: 
      - '**.yml'
      - 'Dockerfile'

jobs:
  call-publisher-flow:
    uses: ./.github/workflows/publish
    with:
      secrets: inherit